python3 lstm_leakage.py --seed 0 --calc_model_leak True --cap_model 'oscar' --mask_bias_source 'obj'
python3 lstm_leakage.py --seed 12 --calc_model_leak True --cap_model 'oscar' --mask_bias_source 'obj'
python3 lstm_leakage.py --seed 456 --calc_model_leak True --cap_model 'oscar' --mask_bias_source 'obj'
python3 lstm_leakage.py --seed 789 --calc_model_leak True --cap_model 'oscar' --mask_bias_source 'obj'
python3 lstm_leakage.py --seed 100 --calc_model_leak True --cap_model 'oscar' --mask_bias_source 'obj'
python3 lstm_leakage.py --seed 200 --calc_model_leak True --cap_model 'oscar' --mask_bias_source 'obj'
python3 lstm_leakage.py --seed 300 --calc_model_leak True --cap_model 'oscar' --mask_bias_source 'obj'
python3 lstm_leakage.py --seed 400 --calc_model_leak True --cap_model 'oscar' --mask_bias_source 'obj'
python3 lstm_leakage.py --seed 500 --calc_model_leak True --cap_model 'oscar' --mask_bias_source 'obj'
python3 lstm_leakage.py --seed 1234 --calc_model_leak True --cap_model 'oscar' --mask_bias_source 'obj'

python3 lstm_leakage.py --seed 0 --calc_model_leak True --cap_model 'oscar' --mask_bias_source 'person'
python3 lstm_leakage.py --seed 12 --calc_model_leak True --cap_model 'oscar' --mask_bias_source 'person'
python3 lstm_leakage.py --seed 456 --calc_model_leak True --cap_model 'oscar' --mask_bias_source 'person'
python3 lstm_leakage.py --seed 789 --calc_model_leak True --cap_model 'oscar' --mask_bias_source 'person'
python3 lstm_leakage.py --seed 100 --calc_model_leak True --cap_model 'oscar' --mask_bias_source 'person'
python3 lstm_leakage.py --seed 200 --calc_model_leak True --cap_model 'oscar' --mask_bias_source 'person'
python3 lstm_leakage.py --seed 300 --calc_model_leak True --cap_model 'oscar' --mask_bias_source 'person'
python3 lstm_leakage.py --seed 400 --calc_model_leak True --cap_model 'oscar' --mask_bias_source 'person'
python3 lstm_leakage.py --seed 500 --calc_model_leak True --cap_model 'oscar' --mask_bias_source 'person'
python3 lstm_leakage.py --seed 1234 --calc_model_leak True --cap_model 'oscar' --mask_bias_source 'person'

python3 lstm_leakage.py --seed 0 --calc_model_leak True --cap_model 'oscar' --mask_bias_source 'both'
python3 lstm_leakage.py --seed 12 --calc_model_leak True --cap_model 'oscar' --mask_bias_source 'both'
python3 lstm_leakage.py --seed 456 --calc_model_leak True --cap_model 'oscar' --mask_bias_source 'both'
python3 lstm_leakage.py --seed 789 --calc_model_leak True --cap_model 'oscar' --mask_bias_source 'both'
python3 lstm_leakage.py --seed 100 --calc_model_leak True --cap_model 'oscar' --mask_bias_source 'both'
python3 lstm_leakage.py --seed 200 --calc_model_leak True --cap_model 'oscar' --mask_bias_source 'both'
python3 lstm_leakage.py --seed 300 --calc_model_leak True --cap_model 'oscar' --mask_bias_source 'both'
python3 lstm_leakage.py --seed 400 --calc_model_leak True --cap_model 'oscar' --mask_bias_source 'both'
python3 lstm_leakage.py --seed 500 --calc_model_leak True --cap_model 'oscar' --mask_bias_source 'both'
python3 lstm_leakage.py --seed 1234 --calc_model_leak True --cap_model 'oscar' --mask_bias_source 'both'


python3 lstm_leakage.py --seed 0 --calc_model_leak True --cap_model 'sat' --mask_bias_source 'obj'
python3 lstm_leakage.py --seed 12 --calc_model_leak True --cap_model 'sat' --mask_bias_source 'obj'
python3 lstm_leakage.py --seed 456 --calc_model_leak True --cap_model 'sat' --mask_bias_source 'obj'
python3 lstm_leakage.py --seed 789 --calc_model_leak True --cap_model 'sat' --mask_bias_source 'obj'
python3 lstm_leakage.py --seed 100 --calc_model_leak True --cap_model 'sat' --mask_bias_source 'obj'
python3 lstm_leakage.py --seed 200 --calc_model_leak True --cap_model 'sat' --mask_bias_source 'obj'
python3 lstm_leakage.py --seed 300 --calc_model_leak True --cap_model 'sat' --mask_bias_source 'obj'
python3 lstm_leakage.py --seed 400 --calc_model_leak True --cap_model 'sat' --mask_bias_source 'obj'
python3 lstm_leakage.py --seed 500 --calc_model_leak True --cap_model 'sat' --mask_bias_source 'obj'
python3 lstm_leakage.py --seed 1234 --calc_model_leak True --cap_model 'sat' --mask_bias_source 'obj'

python3 lstm_leakage.py --seed 0 --calc_model_leak True --cap_model 'sat' --mask_bias_source 'person'
python3 lstm_leakage.py --seed 12 --calc_model_leak True --cap_model 'sat' --mask_bias_source 'person'
python3 lstm_leakage.py --seed 456 --calc_model_leak True --cap_model 'sat' --mask_bias_source 'person'
python3 lstm_leakage.py --seed 789 --calc_model_leak True --cap_model 'sat' --mask_bias_source 'person'
python3 lstm_leakage.py --seed 100 --calc_model_leak True --cap_model 'sat' --mask_bias_source 'person'
python3 lstm_leakage.py --seed 200 --calc_model_leak True --cap_model 'sat' --mask_bias_source 'person'
python3 lstm_leakage.py --seed 300 --calc_model_leak True --cap_model 'sat' --mask_bias_source 'person'
python3 lstm_leakage.py --seed 400 --calc_model_leak True --cap_model 'sat' --mask_bias_source 'person'
python3 lstm_leakage.py --seed 500 --calc_model_leak True --cap_model 'sat' --mask_bias_source 'person'
python3 lstm_leakage.py --seed 1234 --calc_model_leak True --cap_model 'sat' --mask_bias_source 'person'

python3 lstm_leakage.py --seed 0 --calc_model_leak True --cap_model 'sat' --mask_bias_source 'both'
python3 lstm_leakage.py --seed 12 --calc_model_leak True --cap_model 'sat' --mask_bias_source 'both'
python3 lstm_leakage.py --seed 456 --calc_model_leak True --cap_model 'sat' --mask_bias_source 'both'
python3 lstm_leakage.py --seed 789 --calc_model_leak True --cap_model 'sat' --mask_bias_source 'both'
python3 lstm_leakage.py --seed 100 --calc_model_leak True --cap_model 'sat' --mask_bias_source 'both'
python3 lstm_leakage.py --seed 200 --calc_model_leak True --cap_model 'sat' --mask_bias_source 'both'
python3 lstm_leakage.py --seed 300 --calc_model_leak True --cap_model 'sat' --mask_bias_source 'both'
python3 lstm_leakage.py --seed 400 --calc_model_leak True --cap_model 'sat' --mask_bias_source 'both'
python3 lstm_leakage.py --seed 500 --calc_model_leak True --cap_model 'sat' --mask_bias_source 'both'
python3 lstm_leakage.py --seed 1234 --calc_model_leak True --cap_model 'sat' --mask_bias_source 'both'

