python3 bert_leakage.py --seed 0 --calc_ann_leak True --num_epochs 5 --learning_rate 1e-5 --cap_model 'nic' --align_vocab True 
python3 bert_leakage.py --seed 12 --calc_ann_leak True --num_epochs 5 --learning_rate 1e-5  --cap_model 'nic' --align_vocab True
python3 bert_leakage.py --seed 456 --calc_ann_leak True --num_epochs 5 --learning_rate 1e-5 --cap_model 'nic' --align_vocab True
python3 bert_leakage.py --seed 789 --calc_ann_leak True --num_epochs 5 --learning_rate 1e-5 --cap_model 'nic' --align_vocab True
python3 bert_leakage.py --seed 100 --calc_ann_leak True --num_epochs 5 --learning_rate 1e-5 --cap_model 'nic' --align_vocab True
python3 bert_leakage.py --seed 200 --calc_ann_leak True --num_epochs 5 --learning_rate 1e-5 --cap_model 'nic' --align_vocab True
python3 bert_leakage.py --seed 300 --calc_ann_leak True --num_epochs 5 --learning_rate 1e-5 --cap_model 'nic' --align_vocab True
python3 bert_leakage.py --seed 400 --calc_ann_leak True --num_epochs 5 --learning_rate 1e-5 --cap_model 'nic' --align_vocab True
python3 bert_leakage.py --seed 500 --calc_ann_leak True --num_epochs 5 --learning_rate 1e-5 --cap_model 'nic' --align_vocab True
python3 bert_leakage.py --seed 1234 --calc_ann_leak True --num_epochs 5 --learning_rate 1e-5 --cap_model 'nic' --align_vocab True

python3 bert_leakage.py --seed 0 --calc_ann_leak True --num_epochs 5 --learning_rate 1e-5 --cap_model 'sat' --align_vocab True
python3 bert_leakage.py --seed 12 --calc_ann_leak True --num_epochs 5 --learning_rate 1e-5  --cap_model 'sat' --align_vocab True
python3 bert_leakage.py --seed 456 --calc_ann_leak True --num_epochs 5 --learning_rate 1e-5 --cap_model 'sat' --align_vocab True
python3 bert_leakage.py --seed 789 --calc_ann_leak True --num_epochs 5 --learning_rate 1e-5 --cap_model 'sat' --align_vocab True
python3 bert_leakage.py --seed 100 --calc_ann_leak True --num_epochs 5 --learning_rate 1e-5 --cap_model 'sat' --align_vocab True
python3 bert_leakage.py --seed 200 --calc_ann_leak True --num_epochs 5 --learning_rate 1e-5 --cap_model 'sat' --align_vocab True
python3 bert_leakage.py --seed 300 --calc_ann_leak True --num_epochs 5 --learning_rate 1e-5 --cap_model 'sat' --align_vocab True
python3 bert_leakage.py --seed 400 --calc_ann_leak True --num_epochs 5 --learning_rate 1e-5 --cap_model 'sat' --align_vocab True
python3 bert_leakage.py --seed 500 --calc_ann_leak True --num_epochs 5 --learning_rate 1e-5 --cap_model 'sat' --align_vocab True
python3 bert_leakage.py --seed 1234 --calc_ann_leak True --num_epochs 5 --learning_rate 1e-5 --cap_model 'sat' --align_vocab True

python3 bert_leakage.py --seed 0 --calc_ann_leak True --num_epochs 5 --learning_rate 1e-5 --cap_model 'fc' --align_vocab True
python3 bert_leakage.py --seed 12 --calc_ann_leak True --num_epochs 5 --learning_rate 1e-5  --cap_model 'fc' --align_vocab True
python3 bert_leakage.py --seed 456 --calc_ann_leak True --num_epochs 5 --learning_rate 1e-5 --cap_model 'fc' --align_vocab True
python3 bert_leakage.py --seed 789 --calc_ann_leak True --num_epochs 5 --learning_rate 1e-5 --cap_model 'fc' --align_vocab True
python3 bert_leakage.py --seed 100 --calc_ann_leak True --num_epochs 5 --learning_rate 1e-5 --cap_model 'fc' --align_vocab True
python3 bert_leakage.py --seed 200 --calc_ann_leak True --num_epochs 5 --learning_rate 1e-5 --cap_model 'fc' --align_vocab True
python3 bert_leakage.py --seed 300 --calc_ann_leak True --num_epochs 5 --learning_rate 1e-5 --cap_model 'fc' --align_vocab True
python3 bert_leakage.py --seed 400 --calc_ann_leak True --num_epochs 5 --learning_rate 1e-5 --cap_model 'fc' --align_vocab True
python3 bert_leakage.py --seed 500 --calc_ann_leak True --num_epochs 5 --learning_rate 1e-5 --cap_model 'fc' --align_vocab True
python3 bert_leakage.py --seed 1234 --calc_ann_leak True --num_epochs 5 --learning_rate 1e-5 --cap_model 'fc' --align_vocab True

python3 bert_leakage.py --seed 0 --calc_ann_leak True --num_epochs 5 --learning_rate 1e-5 --cap_model 'att2in' --align_vocab True
python3 bert_leakage.py --seed 12 --calc_ann_leak True --num_epochs 5 --learning_rate 1e-5  --cap_model 'att2in' --align_vocab True
python3 bert_leakage.py --seed 456 --calc_ann_leak True --num_epochs 5 --learning_rate 1e-5 --cap_model 'att2in' --align_vocab True
python3 bert_leakage.py --seed 789 --calc_ann_leak True --num_epochs 5 --learning_rate 1e-5 --cap_model 'att2in' --align_vocab True
python3 bert_leakage.py --seed 100 --calc_ann_leak True --num_epochs 5 --learning_rate 1e-5 --cap_model 'att2in' --align_vocab True
python3 bert_leakage.py --seed 200 --calc_ann_leak True --num_epochs 5 --learning_rate 1e-5 --cap_model 'att2in' --align_vocab True
python3 bert_leakage.py --seed 300 --calc_ann_leak True --num_epochs 5 --learning_rate 1e-5 --cap_model 'att2in' --align_vocab True
python3 bert_leakage.py --seed 400 --calc_ann_leak True --num_epochs 5 --learning_rate 1e-5 --cap_model 'att2in' --align_vocab True
python3 bert_leakage.py --seed 500 --calc_ann_leak True --num_epochs 5 --learning_rate 1e-5 --cap_model 'att2in' --align_vocab True
python3 bert_leakage.py --seed 1234 --calc_ann_leak True --num_epochs 5 --learning_rate 1e-5 --cap_model 'att2in' --align_vocab True

python3 bert_leakage.py --seed 0 --calc_ann_leak True --num_epochs 5 --learning_rate 1e-5 --cap_model 'updn' --align_vocab True
python3 bert_leakage.py --seed 12 --calc_ann_leak True --num_epochs 5 --learning_rate 1e-5  --cap_model 'updn' --align_vocab True
python3 bert_leakage.py --seed 456 --calc_ann_leak True --num_epochs 5 --learning_rate 1e-5 --cap_model 'updn' --align_vocab True
python3 bert_leakage.py --seed 789 --calc_ann_leak True --num_epochs 5 --learning_rate 1e-5 --cap_model 'updn' --align_vocab True
python3 bert_leakage.py --seed 100 --calc_ann_leak True --num_epochs 5 --learning_rate 1e-5 --cap_model 'updn' --align_vocab True
python3 bert_leakage.py --seed 200 --calc_ann_leak True --num_epochs 5 --learning_rate 1e-5 --cap_model 'updn' --align_vocab True
python3 bert_leakage.py --seed 300 --calc_ann_leak True --num_epochs 5 --learning_rate 1e-5 --cap_model 'updn' --align_vocab True
python3 bert_leakage.py --seed 400 --calc_ann_leak True --num_epochs 5 --learning_rate 1e-5 --cap_model 'updn' --align_vocab True
python3 bert_leakage.py --seed 500 --calc_ann_leak True --num_epochs 5 --learning_rate 1e-5 --cap_model 'updn' --align_vocab True
python3 bert_leakage.py --seed 1234 --calc_ann_leak True --num_epochs 5 --learning_rate 1e-5 --cap_model 'updn' --align_vocab True

python3 bert_leakage.py --seed 0 --calc_ann_leak True --num_epochs 5 --learning_rate 1e-5 --cap_model 'transformer' --align_vocab True
python3 bert_leakage.py --seed 12 --calc_ann_leak True --num_epochs 5 --learning_rate 1e-5  --cap_model 'transformer' --align_vocab True
python3 bert_leakage.py --seed 456 --calc_ann_leak True --num_epochs 5 --learning_rate 1e-5 --cap_model 'transformer' --align_vocab True
python3 bert_leakage.py --seed 789 --calc_ann_leak True --num_epochs 5 --learning_rate 1e-5 --cap_model 'transformer' --align_vocab True
python3 bert_leakage.py --seed 100 --calc_ann_leak True --num_epochs 5 --learning_rate 1e-5 --cap_model 'transformer' --align_vocab True
python3 bert_leakage.py --seed 200 --calc_ann_leak True --num_epochs 5 --learning_rate 1e-5 --cap_model 'transformer' --align_vocab True
python3 bert_leakage.py --seed 300 --calc_ann_leak True --num_epochs 5 --learning_rate 1e-5 --cap_model 'transformer' --align_vocab True
python3 bert_leakage.py --seed 400 --calc_ann_leak True --num_epochs 5 --learning_rate 1e-5 --cap_model 'transformer' --align_vocab True
python3 bert_leakage.py --seed 500 --calc_ann_leak True --num_epochs 5 --learning_rate 1e-5 --cap_model 'transformer' --align_vocab True
python3 bert_leakage.py --seed 1234 --calc_ann_leak True --num_epochs 5 --learning_rate 1e-5 --cap_model 'transformer' --align_vocab True

python3 bert_leakage.py --seed 0 --calc_ann_leak True --num_epochs 5 --learning_rate 1e-5 --cap_model 'oscar' --align_vocab True
python3 bert_leakage.py --seed 12 --calc_ann_leak True --num_epochs 5 --learning_rate 1e-5  --cap_model 'oscar' --align_vocab True
python3 bert_leakage.py --seed 456 --calc_ann_leak True --num_epochs 5 --learning_rate 1e-5 --cap_model 'oscar' --align_vocab True
python3 bert_leakage.py --seed 789 --calc_ann_leak True --num_epochs 5 --learning_rate 1e-5 --cap_model 'oscar' --align_vocab True
python3 bert_leakage.py --seed 100 --calc_ann_leak True --num_epochs 5 --learning_rate 1e-5 --cap_model 'oscar' --align_vocab True
python3 bert_leakage.py --seed 200 --calc_ann_leak True --num_epochs 5 --learning_rate 1e-5 --cap_model 'oscar' --align_vocab True
python3 bert_leakage.py --seed 300 --calc_ann_leak True --num_epochs 5 --learning_rate 1e-5 --cap_model 'oscar' --align_vocab True
python3 bert_leakage.py --seed 400 --calc_ann_leak True --num_epochs 5 --learning_rate 1e-5 --cap_model 'oscar' --align_vocab True
python3 bert_leakage.py --seed 500 --calc_ann_leak True --num_epochs 5 --learning_rate 1e-5 --cap_model 'oscar' --align_vocab True
python3 bert_leakage.py --seed 1234 --calc_ann_leak True --num_epochs 5 --learning_rate 1e-5 --cap_model 'oscar' --align_vocab True

python3 bert_leakage.py --seed 0 --calc_ann_leak True --num_epochs 5 --learning_rate 1e-5 --cap_model 'nic_equalizer' --align_vocab True
python3 bert_leakage.py --seed 12 --calc_ann_leak True --num_epochs 5 --learning_rate 1e-5  --cap_model 'nic_equalizer' --align_vocab True
python3 bert_leakage.py --seed 456 --calc_ann_leak True --num_epochs 5 --learning_rate 1e-5 --cap_model 'nic_equalizer' --align_vocab True
python3 bert_leakage.py --seed 789 --calc_ann_leak True --num_epochs 5 --learning_rate 1e-5 --cap_model 'nic_equalizer' --align_vocab True
python3 bert_leakage.py --seed 100 --calc_ann_leak True --num_epochs 5 --learning_rate 1e-5 --cap_model 'nic_equalizer' --align_vocab True
python3 bert_leakage.py --seed 200 --calc_ann_leak True --num_epochs 5 --learning_rate 1e-5 --cap_model 'nic_equalizer' --align_vocab True
python3 bert_leakage.py --seed 300 --calc_ann_leak True --num_epochs 5 --learning_rate 1e-5 --cap_model 'nic_equalizer' --align_vocab True
python3 bert_leakage.py --seed 400 --calc_ann_leak True --num_epochs 5 --learning_rate 1e-5 --cap_model 'nic_equalizer' --align_vocab True
python3 bert_leakage.py --seed 500 --calc_ann_leak True --num_epochs 5 --learning_rate 1e-5 --cap_model 'nic_equalizer' --align_vocab True
python3 bert_leakage.py --seed 1234 --calc_ann_leak True --num_epochs 5 --learning_rate 1e-5 --cap_model 'nic_equalizer' --align_vocab True

python3 bert_leakage.py --seed 0 --calc_ann_leak True --num_epochs 5 --learning_rate 1e-5 --cap_model 'nic_plus' --align_vocab True
python3 bert_leakage.py --seed 12 --calc_ann_leak True --num_epochs 5 --learning_rate 1e-5  --cap_model 'nic_plus' --align_vocab True
python3 bert_leakage.py --seed 456 --calc_ann_leak True --num_epochs 5 --learning_rate 1e-5 --cap_model 'nic_plus' --align_vocab True
python3 bert_leakage.py --seed 789 --calc_ann_leak True --num_epochs 5 --learning_rate 1e-5 --cap_model 'nic_plus' --align_vocab True
python3 bert_leakage.py --seed 100 --calc_ann_leak True --num_epochs 5 --learning_rate 1e-5 --cap_model 'nic_plus' --align_vocab True
python3 bert_leakage.py --seed 200 --calc_ann_leak True --num_epochs 5 --learning_rate 1e-5 --cap_model 'nic_plus' --align_vocab True
python3 bert_leakage.py --seed 300 --calc_ann_leak True --num_epochs 5 --learning_rate 1e-5 --cap_model 'nic_plus' --align_vocab True
python3 bert_leakage.py --seed 400 --calc_ann_leak True --num_epochs 5 --learning_rate 1e-5 --cap_model 'nic_plus' --align_vocab True
python3 bert_leakage.py --seed 500 --calc_ann_leak True --num_epochs 5 --learning_rate 1e-5 --cap_model 'nic_plus' --align_vocab True
python3 bert_leakage.py --seed 1234 --calc_ann_leak True --num_epochs 5 --learning_rate 1e-5 --cap_model 'nic_plus' --align_vocab True

